# Generated by Django 4.2.4 on 2023-08-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='barrio',
            field=models.CharField(default=12312, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denuncia',
            name='calderon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='calle_principal',
            field=models.CharField(default=12312, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denuncia',
            name='calle_transversal',
            field=models.CharField(default=12132, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denuncia',
            name='cedula',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='centro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='delicia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='direccion_referencia',
            field=models.CharField(default=1232, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denuncia',
            name='email',
            field=models.EmailField(default=12312, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denuncia',
            name='numero_casa',
            field=models.CharField(default=2312, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denuncia',
            name='numero_casilla_judicial',
            field=models.CharField(default=12312, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denuncia',
            name='numero_celular',
            field=models.CharField(default=21312, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denuncia',
            name='numero_documento',
            field=models.CharField(default=2312, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denuncia',
            name='numero_telefonico',
            field=models.CharField(default=123123, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denuncia',
            name='parentesco_nna',
            field=models.CharField(default=1323, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denuncia',
            name='parroquia',
            field=models.CharField(default=2312, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denuncia',
            name='pasaporte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='quitumbe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='sector',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
