# Generated by Django 4.2.5 on 2023-09-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncia', '0002_denuncia_barrio_denuncia_calderon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demandado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.BooleanField(default=False)),
                ('pasaporte', models.BooleanField(default=False)),
                ('calle_principal', models.CharField(max_length=100)),
                ('numero_casa', models.CharField(max_length=100)),
                ('calle_transversal', models.CharField(max_length=100)),
                ('direccion_referencia', models.CharField(max_length=100)),
                ('parroquia', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('barrio', models.CharField(max_length=100)),
                ('numero_telefonico', models.CharField(max_length=10)),
                ('numero_celular', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('numero_casilla_judicial', models.CharField(max_length=10)),
                ('parentesco_nna', models.CharField(max_length=50)),
                ('nombre_laburo', models.CharField(max_length=50)),
                ('calle_principal_laburo', models.CharField(max_length=90)),
                ('numero_direccion', models.CharField(max_length=10)),
                ('calle_transversal_laburo', models.CharField(max_length=90)),
                ('referencia_laburo', models.CharField(max_length=90)),
                ('parroquia_laburo', models.CharField(max_length=90)),
                ('sector_laburo', models.CharField(max_length=90)),
                ('barrio_laburo', models.CharField(max_length=90)),
                ('numero_contacto', models.CharField(max_length=10)),
            ],
        ),
    ]
